### ISSUE TITLE
Make call for abstracts

### ISSUE THREAD

**Issue by FlanFlanagan** [ergs/twofcs.ergs.sc.edu#2]

**Comment by katyhuff** [comment]
I think this can be closed, but I have no permission to close it.

**Comment by katyhuff** [comment]
@FlanFlanagan I still don't have permission to close this, but it's certainly done. Can you close this for me? -- I am assigned to it, so it's cluttering my list of open issues on github. .  . a list which helps to determine what I do every day.

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8255210-116454032_15-s1-v1.png?transparent=1&palette=1&width=246)
